apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sensu-operator
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: sensu-operator
    spec:
      containers:
      - name: sensu-operator
        image: objectrocket/sensu-operator:v0.0.1
        command:
        - sensu-operator
        # Uncomment to act for resources in all namespaces. More information in doc/clusterwide.md
        #- -cluster-wide
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
