---
apiVersion: v1
kind: Namespace
metadata:
  name: sensu

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sensu-operator
  namespace: sensu

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensu-operator
  namespace: sensu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensu-operator
      release: sensu-operator
  template:
    metadata:
      labels:
        name: sensu-operator
        release: sensu-operator
        app: sensu-operator
    spec:
      containers:
      - name: sensu-operator
        image: objectrocket/sensu-operator:0.10.2-rc9
        imagePullPolicy: Always
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SENSUOP_LOG_LEVEL
          value: debug
        - name: SENSUOP_CLUSTER_WIDE
          value: "true"
        - name: SENSUOP_RESYNC_INTERVAL
          value: 5m
        - name: SENSUOP_GC_INTERVAL
          value: 10m
        - name: SENSUOP_WORKER_THREADS
          value: "4"
        - name: SENSUOP_PROCESSING_RETRIES
          value: "5"
        imagePullSecrets:
          - name: 'or-docker-secret'
