apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dummy-service
  namespace: sensu
spec:
  replicas: 2
  template:
    metadata:
      name: dummy-service
      namespace: sensu
      labels:
        app: dummy-service
    spec:
      containers:
        - name: sensu-agent
          image: sensu/sensu:5.1.0
          command: ["/opt/sensu/bin/sensu-agent", "start"]
          env:
            - name: SENSU_BACKEND_URL
              value: ws://platdev0-agent.sensu.svc.cluster.local:8081
            - name: SENSU_SUBSCRIPTIONS
              value: dummy
            - name: SENSU_NAMESPACE
              value: platform
            - name: SENSU_DEREGISTER
              value: "true"
            - name: SENSU_LABELS
              value: '{"k8s_node": "true"}'

        - name: dummy-service
          image: busybox
          command: ["/bin/sleep", "100000"]
