apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dummy-service
spec:
  replicas: 1
  template:
    metadata:
      name: dummy-service
      labels:
        app: dummy-service
    spec:
      containers:
        - name: sensu-agent
          image: sensu/sensu:5.1.0
          command: ["/opt/sensu/bin/sensu-agent", "start", "--log-level", "debug"]
          env:
            - name: SENSU_BACKEND_URL
              value: ws://sensu-agent.sensu.svc.cluster.local:8081
            - name: SENSU_SUBSCRIPTIONS
              value: test
        - name: dummy-service
          image: busybox
          command: ["/bin/sleep", "100000"]
