apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dummy-service
spec:
  replicas: 2
  template:
    metadata:
      name: dummy-service
      labels:
        app: dummy-service
    spec:
      containers:
        - name: sensu-agent
          image: sensu/sensu:5.1.0
          command: ["/opt/sensu/bin/sensu-agent", "start"]
          env:
            - name: SENSU_BACKEND_URL
              value: ws://example-sensu-cluster-agent.default.svc.cluster.local:8081
            - name: SENSU_SUBSCRIPTIONS
              value: dummy
        - name: dummy-service
          image: busybox
          command: ["/bin/sleep", "100000"]
      nodeSelector:
        node-role.kubernetes.io/platform_worker: "true"

      tolerations:
        - key: "node_role"
          operator: "Equal"
          value: "platform_worker"
          effect: "NoSchedule"
