apiVersion: "objectrocket.com/v1beta1"
kind: "SensuAsset"
metadata:
  name: "example-sensu-asset"
  ## Adding this annotation make this cluster managed by clusterwide operators
  ## namespaced operators ignore it
  # annotations:
  #   objectrocket.com/scope: clusterwide
spec:
  url: "https://s3.aws.amazon.com/objectrocket/sensuasserts/example.asset"
  sha512: "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e"
  filter: []
