apiVersion: objectrocket.com/v1beta1
kind: SensuCluster
metadata:
  annotations:
    objectrocket.com/scope: clusterwide
  name: platdev0
  namespace: sensu
spec:
  pod:
    resources: {}
    persistentVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
      storageClassName: standard
  repository: sensu/sensu
  size: 1
  version: 5.14.0
