apiVersion: objectrocket.com/v1beta1
kind: SensuCluster
metadata:
  annotations:
    objectrocket.com/scope: clusterwide
  name: orsensu
  namespace: sensu
spec:
  pod:
    resources: {}
    persistentVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
      storageClassName: gp2
  repository: objectrocket/sensu-backend
  size: 5
  version: 5.20.2_or2
  clusteradminusername: admin
  clusteradminpassword: p@ssw0rd!
