apiVersion: objectrocket.com/v1beta1
kind: SensuCluster
metadata:
  annotations:
    objectrocket.com/scope: clusterwide
  name: sensu
  namespace: sensu
spec:
  pod:
    resources: {}
    persistentVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
      storageClassName: standard
  repository: objectrocket/sensu-backend
  size: 1
  version: 5.20.2_or1
  clusteradminusername: "admin"
  clusteradminpassword: "P@ssw0rd!"
