apiVersion: v1
kind: Service
metadata:
  name: example-sensu-cluster-external
spec:
  type: NodePort
  ports:
  - name: dashboard
    nodePort: 31900
    port: 3000
    protocol: TCP
  - name: api
    nodePort: 31980
    port: 8080
    protocol: TCP
  - name: agent
    nodePort: 31981
    port: 8081
    protocol: TCP
  selector:
    sensu_cluster: sensu
