apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: <ROLE_NAME>
  namespace: <NAMESPACE>
rules:
- apiGroups:
  - objectrocket.com
  resources:
  - sensuclusters
  - sensubackups
  - sensurestores
  - sensuassets
  - sensucheckconfigs
  - sensuhandlers
  - sensueventfilters
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - "*"
# The following permissions can be removed if not using S3 backup and TLS
- apiGroups:
  - ""
  resources:
  - secrets
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - "*"
# For using pod security policies
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - default
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
