apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: <ROLE_NAME>
  namespace: <NAMESPACE>
rules:
- apiGroups:
  - objectrocket.com
  resources:
  - sensuclusters
  - sensubackups
  - sensurestores
  - sensuassets
  - sensuhandlers
  - sensucheckconfigs
  - sensueventfilters
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - nodes
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - "*"
# The following permissions can be removed if not using S3 backup and TLS
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
