---
apiVersion: objectrocket.com/v1beta1
kind: SensuCheckConfig
metadata:
  name: sensu-checkconfig-google
  namespace: sensu
  finalizers:
  - checkconfig.finalizer.objectrocket.com
spec:
  command: check-http -u https://www.google.com/
  publish: true
  subscriptions:
  - test
  interval: 15
  runtime_assets:
  - sensu-asset-http
  sensuMetadata:
    name: sensu-checkconfig-google
    clusterName: platdev0
    namespace: default
