---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: or-sensu-operator
  labels:
    app: or-sensu-operator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: or-sensu-operator
  template:
    metadata:
      labels:
        app: or-sensu-operator
        name: or-sensu-operator
    spec:
      containers:
      - name: sensu-operator
        image: {{ .Values.image.repository }}:{{ .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
          {{- range .Values.resourceSettings.limit }}
            {{ .name }}: {{ .value }}
          {{- end }}
          requests:
          {{- range .Values.resourceSettings.request }}
            {{ .name }}: {{ .value }}
          {{- end }}
        command:
        - sensu-operator
{{- if .Values.sensu.clusterWide }}
        - -cluster-wide
{{- end }}
        - -logtostderr
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
{{- if .Values.enableAdminToken }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret.name }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
