---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sensu-operator.fullname" . }}-headless
  labels:
    app: {{ include "sensu-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - name: http
    port: 8080
  clusterIP: None
  selector:
    app: {{ include "sensu-operator.name" . }}
    release: {{ .Release.Name }}
    name: {{ template "sensu-operator.fullname" . }}
