version: 2
jobs:
  markdownlint:
    docker:
      - image: circleci/node:10.14.2
    steps:
      - checkout
      - run:
          name: install markdownlint
          command: |
            sudo npm install -g markdownlint-cli
            markdownlint --version
      - run:
          name: lint README.md
          command: markdownlint --config .markdownlint.json README.md
  build:
    working_directory: /go/src/github.com/objectrocket/sensu-operator
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the server binary and docker image
          command: make docker-build IMAGE_VERSION=${CIRCLE_TAG}
  unit_test:
    working_directory: /go/src/github.com/objectrocket/sensu-operator
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run:
          name: go tests
          command: make unittest
  build_deploy:
    working_directory: /go/src/github.com/objectrocket/sensu-operator
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker login
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: docker build and push
          command: |
            make docker-push IMAGE_VERSION=${CIRCLE_TAG}
  helm_push:
    docker:
      - image: circleci/python:3.6
    environment:
      DESIRED_VERSION: "v2.9.1"
    steps:
      - checkout
      - run:
          name: Install Helm
          command: |
            curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
      - run:
          name: Push to S3
          command: hack/helm/push
workflows:
  version: 2
  # runs on all commits
  build_and_test:
    jobs:
      - build
      - unit_test
      - markdownlint
  test_build_deploy:
    jobs:
      - unit_test:
          filters:
            tags:
              only:
                - /^[0-9]+.[0-9]+.[0-9]+$/
                - /^[0-9]+.[0-9]+.[0-9]+-rc[0-9]+$/
            branches:
              ignore: /.*/
      - build_deploy:
          filters:
            tags:
              only:
                - /^[0-9]+.[0-9]+.[0-9]+$/
                - /^[0-9]+.[0-9]+.[0-9]+-rc[0-9]+$/
            branches:
              ignore: /.*/
      - helm_push:
          requires:
            - build_deploy
          filters:
            tags:
              only:
                - /^[0-9]+.[0-9]+.[0-9]+$/
                - /^[0-9]+.[0-9]+.[0-9]+-rc[0-9]+$/
            branches:
              ignore: /.*/
