version: 2.1

references: 
  platform-docker: &docker
    docker:
      - image: objectrocket/platform-cicd:latest
        auth:
          username: ${DOCKER_USERNAME}
          password: ${DOCKER_PASSWORD}

jobs:
  markdownlint:
    docker:
      - image: circleci/node:10.14.2
    steps:
      - checkout
      - run:
          name: install markdownlint
          command: |
            sudo npm install -g markdownlint-cli
            markdownlint --version
      - run:
          name: lint README.md
          command: markdownlint --config .markdownlint.json README.md
  build:
    working_directory: /go/src/github.com/objectrocket/sensu-operator
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the server binary and docker image
          command: make docker-build IMAGE_VERSION=latest
  unit_test:
    working_directory: /go/src/github.com/objectrocket/sensu-operator
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run:
          name: go tests
          command: make unittest
  build_deploy:
    working_directory: /go/src/github.com/objectrocket/sensu-operator
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker login
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: docker build and push
          command: |
            make docker-push IMAGE_VERSION=${CIRCLE_TAG}
  helm_push:
    <<: *docker
    environment:
      CHARTSDIR: helm
    steps:
      - checkout
      - run:
          name: Push to S3
          command: ~/ci-scripts/helm_push.sh
  update-default:
    <<: *docker
    environment:
      CHARTSDIR: helm
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "69:52:7a:2e:29:b7:ba:aa:5e:59:98:14:f9:8b:d4:ae"   
      - run:
          name: add helm repo
          command: ~/ci-scripts/helm_add_repo.sh
      - run:
          name: update default cluster
          command: ~/ci-scripts/update-default-cluster.sh
workflows:
  version: 2
  # runs on all commits
  build_and_test:
    jobs:
      - build
      - unit_test
      - markdownlint
  test_build_deploy:
    jobs:
      - unit_test:
          filters:
            tags:
              only:
                - /^[0-9]+.[0-9]+.[0-9]+$/
                - /^[0-9]+.[0-9]+.[0-9]+-rc[0-9]+$/
            branches:
              ignore: /.*/
      - build_deploy:
          filters:
            tags:
              only:
                - /^[0-9]+.[0-9]+.[0-9]+$/
                - /^[0-9]+.[0-9]+.[0-9]+-rc[0-9]+$/
            branches:
              ignore: /.*/
      - helm_push:
          requires:
            - build_deploy
          filters:
            tags:
              only:
                - /^[0-9]+.[0-9]+.[0-9]+$/
                - /^[0-9]+.[0-9]+.[0-9]+-rc[0-9]+$/
            branches:
              ignore: /.*/
      - update-default:
          requires:
            - build_deploy
            - helm_push
          filters:
            tags:
              only:
                - /^[0-9]+.[0-9]+.[0-9]+$/
            branches:
              ignore: /.*/
